server:  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: hr-payroll        uri: lb://hr-payroll/
        predicates:
        - Path=/payments/**
      - id: hr-worker        uri: lb://hr-worker/
        predicates:
        - Path=/**  application:    name: hr-api-gateway-springcloud